### ISSUE TITLE
[Mod-Support] Immersive Engineering/Integration Posts

### ISSUE THREAD

**Issue by Voxel-Friend** [Cream-Tea/Railcraft-Cosmetic-Additions#4]
![2016-05-30_04 03 24](https://cloud.githubusercontent.com/assets/12395262/15645093/325a5684-261c-11e6-8a9a-e90a616d5bcb.png)
Would like to use [IE](http://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering) and [II](http://minecraft.curseforge.com/projects/immersive-integration) posts (Wooden, Aluminum, Steel) on platforms. Should make for some nice looking stations.

**Comment by Cream-Tea** [comment]
I've just realised, Surely I could just make it so **any** block placed on top makes the platform change it's shape?

If it's a normal block, you wouldn't know the different.

If it's a fence or other small block, it will adapt it's shape?

That would save us a lot of chasing down dev versions of mods etc...

**Comment by hanakocz** [comment]
No, there are blocks that are still solid, but translucent. We would need to blacklist some to connect, or whitelist some to connect. At this point, it is easier to whitelist the good ones, not only because the code works that way already, but because there are also two variants of connection already - compare stone wall and fence.

Also as I said in comment, there is function half prepared for this (if I remember well the name- on phone now) , called chechblockabove - which we just will extend with more (in this thing optional) ifs for another blocks.
