### ISSUE TITLE
[Derp] Platform Edge with Line

### ISSUE THREAD

**Issue by Voxel-Friend** [Cream-Tea/Railcraft-Cosmetic-Additions#6]
![2016-05-30_04 04 02](https://cloud.githubusercontent.com/assets/12395262/15645116/527b9806-261c-11e6-8479-5d0302d5b574.png)

**Comment by Cream-Tea** [comment]
Well, I never intended to have 90 degree platforms. But it can be a thing if people want it sure!

**Comment by Voxel-Friend** [comment]
It really bothered me as well. Thanks!

**Comment by hanakocz** [comment]
Ya I know about this since I added the shape changing, however still not got proper idea how to deal with the line (maybe we will need to use texture map or so, but nothing like easy system it is used now),  there is also more things about it (for now it would not work to place nonlined into corner with lined ones adjacent, for example), but we did not wanted to hold other news by this cosmetic issue.
